In [ ]:
#Importar librería Pandas
import pandas as pd

In [ ]:
#Crear una serie de 5 elementos numéricos
series = pd.Series( [5, 10, 15, 20, 25] )
series

0     5
1    10
2    15
3    20
4    25
dtype: int64

In [ ]:
#Conocer el tipo de dato
type(series)

pandas.core.series.Series

In [ ]:
#Obtener el índice 3
series[3]

20

In [ ]:
#Crear una serie de  caracteres con 3 elementos
cad = pd.Series( ['U', 'T', 'P'] )
cad

0    U
1    T
2    P
dtype: object

In [ ]:
# Crear una DataFrames
lst = ['Hola', 'mundo', 'robótico']
df = pd.DataFrame(lst)
print(df)

          0
0      Hola
1     mundo
2  robótico

In [ ]:
# Estructura de datos con cabecera
data = { 'Nombre': ['Juan', 'Ana', 'Jose', 'Arturo' ], 
        'Edad' : [25, 18, 23, 27], 
        'Pais': ['MX', 'CO', 'BR', 'PE'] }
df = pd.DataFrame(data)
df

   Nombre  Edad Pais
0    Juan    25   MX
1     Ana    18   CO
2    Jose    23   BR
3  Arturo    27   PE

In [ ]:
#Imprimir dos columnas de estructura de datos 
print(df[[ 'Nombre', 'Pais' ]])

   Nombre Pais
0    Juan   MX
1     Ana   CO
2    Jose   BR
3  Arturo   PE

In [ ]:
#Cargar una estructura de datos y mostrar los 5 primeros elementos
data = pd.read_csv('canciones_2022.csv')
data.head(5)

,id,name,artists,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature
0,6DCZcSspjsKoFjzjrWoCd,God's Plan,Drake,0.754,0.449,7.0,-9.211,1.0,0.1090,0.0332,0.000083,0.552,0.357,77.169,198973.0,4.0
1,3ee8Jmje8o58CHK66QrVC,SAD!,XXXTENTACION,0.740,0.613,8.0,-4.880,1.0,0.1450,0.2580,0.003720,0.123,0.473,75.023,166606.0,4.0
2,0e7ipj03S05BNilyu5bRz,rockstar (feat. 21 Savage),Post Malone,0.587,0.535,5.0,-6.090,0.0,0.0898,0.1170,0.000066,0.131,0.140,159.847,218147.0,4.0
3,3swc6WTsr7rl9DqQKQA55,Psycho (feat. Ty Dolla $ign),Post Malone,0.739,0.559,8.0,-8.011,1.0,0.1170,0.5800,0.000000,0.112,0.439,140.124,221440.0,4.0
4,2G7V7zsVDxg1yRsu7Ew9R,In My Feelings,Drake,0.835,0.626,1.0,-5.833,1.0,0.1250,0.0589,0.000060,0.396,0.350,91.030,217925.0,4.0

In [ ]:
#Imprimir un dato específico 
artista = data.artists
artista[2]

'Post Malone'

In [ ]:
#Mostar la información una fila en específico
info = data.iloc[2]
info

id                       0e7ipj03S05BNilyu5bRz
name                rockstar (feat. 21 Savage)
artists                            Post Malone
danceability                             0.587
energy                                   0.535
key                                        5.0
loudness                                 -6.09
mode                                       0.0
speechiness                             0.0898
acousticness                             0.117
instrumentalness                      0.000066
liveness                                 0.131
valence                                   0.14
tempo                                  159.847
duration_ms                           218147.0
time_signature                             4.0
Name: 2, dtype: object

In [ ]:
#Mostrar los últimos registros de la estructura
data.tail()

,id,name,artists,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature
95,630sXRhIcfwr2e4RdNtjK,Rewrite The Stars,Zac Efron,0.684,0.619,10.0,-7.005,1.0,0.0386,0.0716,0.000000,0.1220,0.2840,125.046,217440.0,4.0
96,2xmrfQpmS2iJExTlklLoA,I Miss You (feat. Julia Michaels),Clean Bandit,0.638,0.658,3.0,-6.318,1.0,0.0456,0.2450,0.000004,0.0919,0.3300,105.076,205748.0,4.0
97,5WvAo7DNuPRmk4APhdPzi,No Brainer,DJ Khaled,0.552,0.760,0.0,-4.706,1.0,0.3420,0.0733,0.000000,0.0865,0.6390,135.702,260000.0,5.0
98,1j4kHkkpqZRBwE0A4CN4Y,Dusk Till Dawn - Radio Edit,ZAYN,0.258,0.437,11.0,-6.593,0.0,0.0390,0.1010,0.000001,0.1060,0.0967,180.043,239000.0,4.0
99,3EPXxR3ImUwfayaurPi3c,Be Alright,Dean Lewis,0.553,0.586,11.0,-6.319,1.0,0.0362,0.6970,0.000000,0.0813,0.4430,126.684,196373.0,4.0

In [ ]:
# Conocer el tamaño del Datasets
data.shape

(100, 16)

In [ ]:
#Conocer las columnas del Datasets
data.columns

Index(['id', 'name', 'artists', 'danceability', 'energy', 'key', 'loudness',
       'mode', 'speechiness', 'acousticness', 'instrumentalness', 'liveness',
       'valence', 'tempo', 'duration_ms', 'time_signature'],
      dtype='object')

In [ ]:
#Obtener el resumen del Datasets
data['tempo'].describe()

count    100.000000
mean     119.904180
std       28.795984
min       64.934000
25%       95.730750
50%      120.116000
75%      140.022750
max      198.075000
Name: tempo, dtype: float64

In [ ]:
#Ordenar datos
data.sort_index(axis = 0, ascending = False)

,id,name,artists,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature
99,3EPXxR3ImUwfayaurPi3c,Be Alright,Dean Lewis,0.553,0.586,11.0,-6.319,1.0,0.0362,0.6970,0.000000,0.0813,0.4430,126.684,196373.0,4.0
98,1j4kHkkpqZRBwE0A4CN4Y,Dusk Till Dawn - Radio Edit,ZAYN,0.258,0.437,11.0,-6.593,0.0,0.0390,0.1010,0.000001,0.1060,0.0967,180.043,239000.0,4.0
97,5WvAo7DNuPRmk4APhdPzi,No Brainer,DJ Khaled,0.552,0.760,0.0,-4.706,1.0,0.3420,0.0733,0.000000,0.0865,0.6390,135.702,260000.0,5.0
96,2xmrfQpmS2iJExTlklLoA,I Miss You (feat. Julia Michaels),Clean Bandit,0.638,0.658,3.0,-6.318,1.0,0.0456,0.2450,0.000004,0.0919,0.3300,105.076,205748.0,4.0
95,630sXRhIcfwr2e4RdNtjK,Rewrite The Stars,Zac Efron,0.684,0.619,10.0,-7.005,1.0,0.0386,0.0716,0.000000,0.1220,0.2840,125.046,217440.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,2G7V7zsVDxg1yRsu7Ew9R,In My Feelings,Drake,0.835,0.626,1.0,-5.833,1.0,0.1250,0.0589,0.000060,0.3960,0.3500,91.030,217925.0,4.0
3,3swc6WTsr7rl9DqQKQA55,Psycho (feat. Ty Dolla $ign),Post Malone,0.739,0.559,8.0,-8.011,1.0,0.1170,0.5800,0.000000,0.1120,0.4390,140.124,221440.0,4.0
2,0e7ipj03S05BNilyu5bRz,rockstar (feat. 21 Savage),Post Malone,0.587,0.535,5.0,-6.090,0.0,0.0898,0.1170,0.000066,0.1310,0.1400,159.847,218147.0,4.0
1,3ee8Jmje8o58CHK66QrVC,SAD!,XXXTENTACION,0.740,0.613,8.0,-4.880,1.0,0.1450,0.2580,0.003720,0.1230,0.4730,75.023,166606.0,4.0
0,6DCZcSspjsKoFjzjrWoCd,God's Plan,Drake,0.754,0.449,7.0,-9.211,1.0,0.1090,0.0332,0.000083,0.5520,0.3570,77.169,198973.0,4.0